### ISSUE TITLE
Por favor, me adicione a PloneGov-Br

### ISSUE THREAD

**Issue by grazicorazza** [plonegovbr/plonegovbr#19]
Considere que você não precisa ter acesso de escrita aos repositórios da PloneGov-Br para criar um "pull request", relatar um problema, ou fazer perguntas.

# Confirmo que

- [x] Eu compreendo que a PloneGov-Br é dedicada a projetos Plone para a comunidade brasileira.
- [x] Eu seguirei o [código de conduta da comunidade Plone](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct).

# Projetos eu pretendo auxiliar:

- [x] PortalBrasil.edu
- [x] PortalBrasil.gov
- [x] PortalBrasil.jus
- [x] PortalBrasil.leg
- [ ] Outros

# Minha motivação

...

Gracias!

**Comment by grazicorazza** [comment]
OI

**Comment by jhgouveia** [comment]
Convite enviado por e-mail.
