### ISSUE TITLE
Por favor, me adicione a PloneGov-Br

### ISSUE THREAD

**Issue by italo2sanfer** [plonegovbr/plonegovbr#20]
Considere que você não precisa ter acesso de escrita aos repositórios da PloneGov-Br para criar um "pull request", relatar um problema, ou fazer perguntas.

# Confirmo que

- [ x ] Eu compreendo que a PloneGov-Br é dedicada a projetos Plone para a comunidade brasileira.
- [ x ] Eu seguirei o [código de conduta da comunidade Plone](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct).

# Projetos eu pretendo auxiliar:

- [ x ] PortalBrasil.edu
- [ x ] PortalBrasil.gov
- [ ] PortalBrasil.jus
- [ ] PortalBrasil.leg
- [ x ] Outros

# Minha motivação
Ajudar no que puder. Adquirir conhecimento com a ferramenta Plone. Contribuir.
...

Gracias!

**Comment by jhgouveia** [comment]
Convite enviado por e-mail.
